name: API Check
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-api-check
  cancel-in-progress: true
jobs:
  api-check:
    name: API check
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { 'fetch-depth': 0 }
      - name: Install Swift
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: latest
        env:
          SWIFTLY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run API breakage check
        run: swift package diagnose-api-breaking-changes "origin/$GITHUB_BASE_REF"
