name: Generator Unit Test
on:
  workflow_call:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-generator-unit-test
  cancel-in-progress: true
jobs:
  generator-unit-test:
    name: Generator Unit Test
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        toolchain: [latest]
    steps:
      - name: Install Swift
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.toolchain }}
        env:
          SWIFTLY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Resolve Swift dependencies
        run: swift package resolve
        working-directory: ./Generator
      - name: Run Unit Tests
        run: swift test --parallel
        working-directory: ./Generator
