name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: ./.github/workflows/soundness.yaml
  api-check:
    name: API Check
    uses: ./.github/workflows/api-check.yaml
