name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: ./.github/workflows/soundness.yaml

  unit-test:
    name: Unit Test
    uses: ./.github/workflows/unit-test.yaml

  generator-unit-test:
    name: Generator Unit Test
    uses: ./.github/workflows/generator-unit-test.yaml
